FROM python:3.8.3-alpine

WORKDIR /usr/src/app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
    && apk add gcc python3-dev musl-dev libffi-dev openssl-dev make g++

COPY . .
WORKDIR api/api
RUN pip install --upgrade pip; pip install poetry; poetry config virtualenvs.create false; poetry install; poetry add uwsgi
CMD poetry shell; uwsgi --master \
  --single-interpreter \
  --workers $WORKERS \
  --gevent $ASYNC_CORES \
  --protocol http \
  --socket 0.0.0.0:$APP_PORT \
  --module patched:app
